#!/bin/sh

if ! type "http" > /dev/null; then
  echo "Need httpie installed"
  pip install httpie
fi

echo "Starting"
http :5000/alpha name="#1"
http :5000/alpha name="#2"
http :5000/alpha name="#3"
http :5000/beta name="#11" alpha_id:=1
http :5000/beta name="#12" alpha_id:=1
http :5000/beta name="#21" alpha_id:=2
http :5000/beta name="#22" alpha_id:=2
http :5000/beta name="#31" alpha_id:=3
