"""2016-06-01_a96fe4017d89

Revision ID: a96fe4017d89
Revises: None
Create Date: 2016-06-01 19:07:16.905179

"""

# revision identifiers, used by Alembic.
revision = 'a96fe4017d89'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alpha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('alpha_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alpha_id'], ['alpha.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beta')
    op.drop_table('alpha')
    ### end Alembic commands ###
