"""empty message

Revision ID: a96fe4017d89
Revises: None
Create Date: 2016-06-01 19:07:16.905179

"""

# revision identifiers, used by Alembic.
revision = 'a96fe4017d89'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('test_a_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_a_id'], ['test_a.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_b')
    op.drop_table('test_a')
    ### end Alembic commands ###
